/*
 * codec27.c
 *
 *  Created on: 2 сент. 2017 г.
 *      Author: sergey.lapenkov
 */

#include "codec27.h"

/* 8-bit parity lookup table, generated by partab.c */
unsigned char Partab[] =
  { 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
      1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
      1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
      0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
      1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
      0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
      0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
      0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
      1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
      0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
      0, 1, 0, 1, 1, 0, };

/* Convolutionally encode data into binary symbols */
int
encode27 (unsigned char *symbols, unsigned char *data, unsigned int nbytes)
{
  int i;
  int encstate = 0;
  int bitcount = 0;
  unsigned short res = 0;
  uint8_t test;

  for (unsigned int c = 0; c < nbytes; c++)
    {
      res = 0;
      for (i = 7; i >= 0; i--)
	{
	  encstate = (encstate << 1) | ((*data >> i) & 1);
	  res = res << 1;
	  res += Partab[encstate & POLYA];
	  res = res << 1;
	  res += Partab[encstate & POLYA];
	}
      trace_printf ("Count:%i Data:%02x Code:%04x\n", c, *data, res);
      data++;
      *symbols++ = (unsigned char) (res >> 8);
      *symbols++ = (unsigned char) (res & 0x00ff);
    }
  /* Flush out tail */
  res = 0;
  for (i = 15; i >= 0; i--)
    {
      encstate = (encstate << 1);
      res = res << 1;
      res += Partab[encstate & POLYA];
      res = res << 1;
      res += Partab[encstate & POLYA];

    }
  *symbols++ = (unsigned char) (res >> 8);
  *symbols++ = (unsigned char) (res & 0x00ff);
  return 0;
}

/* Generate log-likelihood metrics for 8-bit soft quantized channel
 * assuming AWGN and BPSK
 */
int
gen_met (int mettab[2][256], /* Metric table, [sent sym][rx symbol] */
	 int amp, /* Signal amplitude, units */
	 double noise, /* Relative noise voltage */
	 double bias, /* Metric bias; 0 for viterbi, rate for sequential */
	 int scale /* Scale factor */
	 )
{
  float n;
  int s, bit;
  float metrics[2][256];
  float p0, p1;

  /* Zero is a special value, since this sample includes all
   * lower samples that were clipped to this value, i.e., it
   * takes the whole lower tail of the curve
   */
  float argum = 0.0 - OFFSET + 0.5;
  argum = argum / amp - 1;
  argum = argum / noise;
  p1 = normal (argum); /* P(s|1) */
  trace_printf ("test p1 %f %f %f \n", argum, p1, noise);

  /* Prob of this value occurring for a 0-bit *//* P(s|0) */
  p0 = normal (((0 - OFFSET + 0.5) / amp + 1) / noise);
  metrics[0][0] = log2(2*p0/(p1+p0)) - bias;
  metrics[1][0] = log2(2*p1/(p1+p0)) - bias;

  trace_printf ("test p1 %f p0 %f \n", p1, p0);

  for (s = 1; s < 255; s++)
    {
      /* P(s|1), prob of receiving s given 1 transmitted */
      p1 = normal (((s - OFFSET + 0.5) / amp - 1) / noise)
	  - normal (((s - OFFSET - 0.5) / amp - 1) / noise);

      /* P(s|0), prob of receiving s given 0 transmitted */
      p0 = normal (((s - OFFSET + 0.5) / amp + 1) / noise)
	  - normal (((s - OFFSET - 0.5) / amp + 1) / noise);

#ifdef notdef
      printf("P(%d|1) = %lg, P(%d|0) = %lg\n",s,p1,s,p0);
#endif
      metrics[0][s] = log2(2*p0/(p1+p0)) - bias;
      metrics[1][s] = log2(2*p1/(p1+p0)) - bias;
    }
  /* 255 is also a special value */
  /* P(s|1) */
  p1 = 1 - normal (((255 - OFFSET - 0.5) / amp - 1) / noise);
  /* P(s|0) */
  p0 = 1 - normal (((255 - OFFSET - 0.5) / amp + 1) / noise);

  metrics[0][255] = log2(2*p0/(p1+p0)) - bias;
  metrics[1][255] = log2(2*p1/(p1+p0)) - bias;
#ifdef	notdef
  /* The probability of a raw symbol error is the probability
   * that a 1-bit would be received as a sample with value
   * 0-128. This is the offset normal curve integrated from -Inf to 0.
   */
  printf("symbol Pe = %lg\n",normal(-1/noise));
#endif
  for (bit = 0; bit < 2; bit++)
    {
      for (s = 0; s < 256; s++)
	{
	  /* Scale and round to nearest integer */
	  mettab[bit][s] = floor (metrics[bit][s] * scale + 0.5);
#ifdef	notdef
	  printf("metrics[%d][%d] = %lg, mettab = %d\n",
	      bit,s,metrics[bit][s],mettab[bit][s]);
#endif
	}
    }
  return 0;
}
