/*
 * codec27.c
 *
 *  Created on: 2 сент. 2017 г.
 *      Author: sergey.lapenkov
 */

#include "codec27.h"

/* 8-bit parity lookup table, generated by partab.c */
unsigned char Partab[] = { 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
		0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
		1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
		0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
		0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
		0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
		1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
		1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
		1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
		0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
		1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, };

/* Convolutionally encode data into binary symbols */
int encode27(unsigned char *symbols, unsigned char *data, unsigned int nbytes) {
	int i;
	int encstate = 0;
	int bitcount = 0;
	unsigned short res = 0;

	for (unsigned int c = 0; c < nbytes; c++) {
		res = 0;
		for (i = 7; i >= 0; i--) {
			encstate = (encstate << 1) | ((*data >> i) & 1);
			//*symbols++ = Partab[encstate & POLYA];
			res = res << 1;
			res += Partab[encstate & POLYA];
			//*symbols++ = Partab[encstate & POLYB];
			res = res << 1;
			res += Partab[encstate & POLYA];
		}
		trace_printf("Count:%i Data:%02x Code:%04x\n", c, *data, res);
		data++;
		*symbols++ = (unsigned char) (res >> 8);
		*symbols++ = (unsigned char) (res & 0x00ff);
	}
	/* Flush out tail */
	for (i = 5; i >= 0; i--) {
		encstate = (encstate << 1);
		//*symbols++ = Partab[encstate & POLYA];
//	bitWrite (symbols[bitcount / 83], bitcount++ % 8,
		//Partab[encstate & POLYA]);
		//*symbols++ = Partab[encstate & POLYB];
//	bitWrite (symbols[bitcount / 83], bitcount++ % 8,
		//Partab[encstate & POLYB]);
	}
	return 0;
}

