/*
 * codec27.c
 *
 *  Created on: 2 сент. 2017 г.
 *      Author: sergey.lapenkov
 */

#include "codec27.h"

/* 8-bit parity lookup table, generated by partab.c */
unsigned char Partab[] =
  { 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
      1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
      1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
      0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
      1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
      0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
      0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
      0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
      1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
      0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
      0, 1, 0, 1, 1, 0, };

void
bitWrite (unsigned char *data, unsigned char nbit, unsigned char value)
{
  if (value)
    {
      *data = *data | (0x01 << nbit);
    }
  else
    {
      *data = *data & (0xfe << nbit);
    }
}

int
bitRead (unsigned char *data, unsigned char nbit)
{
  int res = 0;
  return res;
}

/* Convolutionally encode data into binary symbols */
int
encode27 (unsigned char *symbols, unsigned char *data, unsigned int nbytes)
{
  int i;
  int encstate = 0;
  int bitcount = 0;
  unsigned char res;

  while (nbytes-- != 0)
    {
      for (i = 7; i >= 0; i--)
	{
	  encstate = (encstate << 1) | ((*data >> i) & 1);
	  //*symbols++ = Partab[encstate & POLYA];
	  res = Partab[encstate & POLYA];
	  //bitWrite (symbols, bitcount++, Partab[encstate & POLYA]);
	  //*symbols++ = Partab[encstate & POLYB];
	  res = Partab[encstate & POLYA];
	  //bitWrite (symbols, bitcount++, Partab[encstate & POLYB]);
	  if (bitcount >= 8)
	    {
	      symbols++;
	    }
	}
      data++;
    }
  /* Flush out tail */
  for (i = 5; i >= 0; i--)
    {
      encstate = (encstate << 1);
      //*symbols++ = Partab[encstate & POLYA];
//	bitWrite (symbols[bitcount / 83], bitcount++ % 8,
      //Partab[encstate & POLYA]);
      //*symbols++ = Partab[encstate & POLYB];
//	bitWrite (symbols[bitcount / 83], bitcount++ % 8,
      //Partab[encstate & POLYB]);
    }
  return 0;
}

